export const FETCH_INFORMATION_SUCCESS = "FETCH_INFORMATION_SUCCESS";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const CREATE_INFORMATION_SUCCESS = "CREATE_INFORMATION_SUCCESS";

export const REGISTER_USERS_SUCCESS = 'REGISTER_USERS_SUCCESS';
export const REGISTER_USERS_FAILURE = 'REGISTER_USERS_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';