export const FETCH_INFORMATION_SUCCESS = "FETCH_INFORMATION_SUCCESS";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";